import { Product } from './types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Groundnuts',
    slug: 'groundnuts',
    image: '/images/products/groundnuts.png',
    shortDescription: 'Premium Indian groundnuts sourced from Gujarat\'s fertile farmlands, available in multiple varieties for global markets.',
    fullDescription: 'AGRITRADE OVERSEAS supplies premium-grade Indian groundnuts (peanuts) sourced directly from Gujarat\'s most productive farming regions. Our groundnuts are carefully selected, cleaned, and processed to meet the stringent quality standards demanded by international buyers. Available in Bold, Java, and TJ varieties, our groundnuts are ideal for oil extraction, confectionery, and direct consumption markets worldwide.',
    keyFeatures: [
      'Available in Bold, Java, and TJ varieties',
      'High oil content and rich flavor profile',
      'Sourced from Gujarat\'s premium farming regions',
      'Stringent quality checks at every stage',
      'Aflatoxin-tested and compliant with international standards',
      'Available in raw, blanched, and roasted forms',
    ],
    packagingOptions: [
      '25 kg / 50 kg PP bags',
      'Jute bags as per buyer requirement',
      'Vacuum-sealed packaging available',
      'Custom packaging on request',
      'Container loads (20 ft / 40 ft)',
    ],
    metaTitle: 'Premium Groundnuts Exporter from India | AGRITRADE OVERSEAS',
    metaDescription: 'Export-quality Indian groundnuts from Gujarat. Bold, Java & TJ varieties available. Premium sourcing, quality tested, and export-ready packaging.',
    category: 'Grains & Nuts',
  },
  {
    id: 2,
    name: 'Cumin',
    slug: 'cumin',
    image: '/images/products/cumin.png',
    shortDescription: 'Finest quality Indian cumin seeds with exceptional aroma and flavor, processed under strict quality controls.',
    fullDescription: 'AGRITRADE OVERSEAS offers top-grade Indian cumin seeds (Jeera) renowned worldwide for their distinctive aroma, robust flavor, and superior quality. Sourced from the leading cumin-producing regions of Gujarat and Rajasthan, our cumin seeds undergo rigorous cleaning, grading, and quality testing to ensure they meet the expectations of discerning international buyers across the Middle East, Europe, and Americas.',
    keyFeatures: [
      'Sourced from Gujarat and Rajasthan',
      'High volatile oil content for superior aroma',
      'Machine-cleaned and sortex-processed',
      'Available in various purity grades (95%-99.5%)',
      'Singapore/Europe quality compliant',
      'Rich amber color with bold seeds',
    ],
    packagingOptions: [
      '25 kg / 50 kg PP bags',
      'Jute bags with inner polythene lining',
      'Food-grade packaging available',
      'Private labeling on request',
      'Container loads (20 ft / 40 ft)',
    ],
    metaTitle: 'Premium Cumin Seeds Exporter from India | AGRITRADE OVERSEAS',
    metaDescription: 'Export-quality Indian cumin seeds from Gujarat. Superior aroma, high purity grades, and export-ready packaging for global markets.',
    category: 'Spices',
  },
  {
    id: 3,
    name: 'Ajwain',
    slug: 'ajwain',
    image: '/images/products/ajwain.png',
    shortDescription: 'Premium ajwain (carom seeds) with high thymol content, ideal for pharmaceutical and culinary applications.',
    fullDescription: 'AGRITRADE OVERSEAS provides premium-quality ajwain (carom seeds) sourced from the finest growing regions of India. Known for their high thymol content and distinctive aromatic profile, our ajwain seeds serve both culinary and pharmaceutical markets worldwide. Each batch is carefully processed to preserve the essential oils and medicinal properties that make Indian ajwain highly sought after in international markets.',
    keyFeatures: [
      'High thymol content for medicinal value',
      'Bold seed size with uniform grading',
      'Machine-cleaned and moisture-controlled',
      'Suitable for culinary and pharmaceutical use',
      'Rich aromatic profile preserved through careful processing',
      'Pesticide residue tested',
    ],
    packagingOptions: [
      '25 kg / 50 kg PP bags',
      'Food-grade export packaging',
      'Vacuum-sealed options available',
      'Custom packaging for retail markets',
      'Bulk container shipments',
    ],
    metaTitle: 'Premium Ajwain (Carom Seeds) Exporter from India | AGRITRADE OVERSEAS',
    metaDescription: 'Export-quality Indian ajwain with high thymol content. Premium sourcing, quality tested, and packaged for global pharmaceutical and culinary markets.',
    category: 'Spices',
  },
  {
    id: 4,
    name: 'Wheat',
    slug: 'wheat',
    image: '/images/products/wheat.png',
    shortDescription: 'High-grade Indian wheat varieties ideal for milling, baking, and food processing industries worldwide.',
    fullDescription: 'AGRITRADE OVERSEAS exports premium Indian wheat sourced from the major wheat-producing states of India. Our wheat varieties are selected for their superior milling quality, high protein content, and excellent baking characteristics. We supply to flour mills, bakeries, and food processing industries across the globe, ensuring consistent quality with every shipment.',
    keyFeatures: [
      'Multiple varieties: Sharbati, Lokwan, and Durum',
      'High protein content suitable for bread-making',
      'Excellent milling and baking characteristics',
      'Low moisture content for extended shelf life',
      'Cleaned and graded to international standards',
      'Consistent quality across shipments',
    ],
    packagingOptions: [
      '50 kg PP bags',
      'Jute bags with food-grade lining',
      'Bulk vessel shipments available',
      'Custom packaging options',
      'Container loads (20 ft / 40 ft)',
    ],
    metaTitle: 'Premium Wheat Exporter from India | AGRITRADE OVERSEAS',
    metaDescription: 'Export-quality Indian wheat varieties for global milling and baking industries. Sharbati, Lokwan & Durum wheat available.',
    category: 'Grains & Nuts',
  },
  {
    id: 5,
    name: 'Chickpea',
    slug: 'chickpea',
    image: '/images/products/chickpea.png',
    shortDescription: 'Premium Indian chickpeas (Kabuli & Desi) with high nutritional value for global food markets.',
    fullDescription: 'AGRITRADE OVERSEAS supplies premium Indian chickpeas in both Kabuli and Desi varieties to meet the diverse requirements of global food markets. Our chickpeas are sourced from India\'s leading producing regions, carefully cleaned, size-graded, and quality-tested to ensure they meet international food safety and quality standards. Rich in protein and fiber, our chickpeas serve food processing, retail, and institutional markets worldwide.',
    keyFeatures: [
      'Available in Kabuli and Desi varieties',
      'Multiple size grades: 7mm, 8mm, 9mm, 10mm+',
      'High protein and fiber content',
      'Machine-cleaned and polished',
      'Low moisture for long shelf life',
      'Suitable for canning, cooking, and flour production',
    ],
    packagingOptions: [
      '25 kg / 50 kg PP bags',
      'Jute bags with inner lining',
      'Food-grade retail packaging',
      'Bulk container shipments',
      'Custom branding available',
    ],
    metaTitle: 'Premium Chickpea Exporter from India | AGRITRADE OVERSEAS',
    metaDescription: 'Export-quality Indian chickpeas in Kabuli & Desi varieties. Size-graded, quality tested, and packaged for global food markets.',
    category: 'Grains & Nuts',
  },
  {
    id: 6,
    name: 'Fenugreek',
    slug: 'fenugreek',
    image: '/images/products/fenugreek.png',
    shortDescription: 'Top-quality Indian fenugreek seeds with rich golden color and high nutritional value for global markets.',
    fullDescription: 'AGRITRADE OVERSEAS offers premium Indian fenugreek seeds (Methi) sourced from the best growing regions of Rajasthan and Gujarat. Our fenugreek seeds are prized for their golden color, bitter-sweet flavor profile, and high nutritional content. They serve diverse industries including food processing, spice blending, pharmaceutical, and nutraceutical markets across the globe.',
    keyFeatures: [
      'Rich golden color and uniform size',
      'High galactomannan content',
      'Sourced from Rajasthan and Gujarat',
      'Machine-cleaned and sortex-processed',
      'Suitable for food, pharma, and nutraceutical industries',
      'Pesticide residue compliant',
    ],
    packagingOptions: [
      '25 kg / 50 kg PP bags',
      'Food-grade packaging',
      'Vacuum-sealed for freshness',
      'Custom packaging on request',
      'Bulk and container shipments',
    ],
    metaTitle: 'Premium Fenugreek Seeds Exporter from India | AGRITRADE OVERSEAS',
    metaDescription: 'Export-quality Indian fenugreek seeds from Gujarat and Rajasthan. Premium quality for food, pharmaceutical, and nutraceutical industries.',
    category: 'Spices',
  },
  {
    id: 7,
    name: 'Coriander',
    slug: 'coriander',
    image: '/images/products/coriander.png',
    shortDescription: 'Premium Indian coriander seeds known for their citrusy aroma and superior flavor for culinary and industrial use.',
    fullDescription: 'AGRITRADE OVERSEAS exports premium-grade Indian coriander seeds sourced from the fertile farmlands of Rajasthan, Gujarat, and Madhya Pradesh. Recognized globally for their distinctive citrusy aroma and warm flavor profile, our coriander seeds are essential ingredients in spice blends, food processing, and essential oil extraction. Every batch undergoes stringent quality testing for purity, moisture, and essential oil content.',
    keyFeatures: [
      'Eagle and Scooter varieties available',
      'High essential oil content',
      'Citrusy aroma with warm flavor profile',
      'Machine-cleaned and graded',
      'Available in whole seeds and split form',
      'Compliant with international quality standards',
    ],
    packagingOptions: [
      '25 kg / 50 kg PP bags',
      'Jute bags with polythene lining',
      'Export-grade food packaging',
      'Private labeling available',
      'Container loads (20 ft / 40 ft)',
    ],
    metaTitle: 'Premium Coriander Seeds Exporter from India | AGRITRADE OVERSEAS',
    metaDescription: 'Export-quality Indian coriander seeds with superior aroma and flavor. Eagle & Scooter varieties for global culinary and industrial markets.',
    category: 'Spices',
  },
  {
    id: 8,
    name: 'All Types of Grains and Spices',
    slug: 'grains-and-spices',
    image: '/images/products/grains-spices.png',
    shortDescription: 'Comprehensive range of premium Indian grains and spices for diverse global market requirements.',
    fullDescription: 'AGRITRADE OVERSEAS offers a comprehensive range of premium Indian agricultural products beyond our core specialties. From sesame seeds and mustard seeds to turmeric, fennel, and various pulses, we source and export a wide variety of grains and spices to meet the diverse requirements of international buyers. Each product in our extended range undergoes the same rigorous quality controls and careful handling that define our commitment to excellence.',
    keyFeatures: [
      'Extensive product range covering major Indian grains and spices',
      'Sesame seeds, mustard seeds, turmeric, fennel, and more',
      'Various pulses and lentils available',
      'Same quality standards across all products',
      'Flexible sourcing for custom requirements',
      'Consolidated shipments for multiple products',
    ],
    packagingOptions: [
      'Product-specific packaging solutions',
      '25 kg / 50 kg PP bags',
      'Food-grade and retail packaging',
      'Custom packaging and labeling',
      'Mixed container loads available',
    ],
    metaTitle: 'Indian Grains & Spices Exporter | AGRITRADE OVERSEAS',
    metaDescription: 'Complete range of premium Indian grains and spices for export. Sesame, mustard, turmeric, fennel, pulses, and more from AGRITRADE OVERSEAS.',
    category: 'Mixed',
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug);
}

export function getAllProductSlugs(): string[] {
  return products.map((product) => product.slug);
}
